// <auto-generated />
using Consultorio.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Consultorio.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Consultorio.WebAPI.Model.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<int>("DiasAfastado");

                    b.Property<string>("Local");

                    b.Property<string>("NomePaciente");

                    b.Property<string>("Sintomas");

                    b.Property<string>("Status");

                    b.HasKey("AgendaId");

                    b.ToTable("Agendas");
                });
#pragma warning restore 612, 618
        }
    }
}
